version: "3.8"

services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - SERVICES=dynamodb,s3
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "./data/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # frontend:
  #   container_name: frontend
  #   ports:
  #     - "8080:80"
  #   build:
  #     context: ./frontend
  #     dockerfile: frontend.dockerfile
