name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        working-directory: ./app
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        working-directory: ./app
        run: dotnet restore
      - name: Build
        working-directory: ./app
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./app
        run: dotnet test --no-build --verbosity normal
